services:
  - type: web
    name: mppf-privacy-shield
    runtime: python
    buildCommand: bash render_build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromGroup: web
      - key: DEBUG
        value: False
